"""
Exports the five parts of a robot (art/robots/robot00N.blend) to Ogre .mesh + .skeleton with blender2ogre, the
same way the 2011 exporter laid them out, after making the Blender file match what Ogre can play.
Run by scripts/export-robots.ps1:  blender --background art/robots/robot00N.blend --python robot_export.py --
    <out dir> [--save]

Source fixes (Blender is the source of truth, so the game gets exactly what an animator sees in Blender):
  - the scene plays at exactly 30 fps (the 2011 files said 29.97, the game plays 30);
  - bone weights: vertex groups that are no bone removed (2011 leftovers; they deform nothing), normalised, below
    1 % removed (keeping at least one), at most 4 per vertex (Ogre's limit; it used to drop the extra ones itself
    and log a warning), normalised again, until stable;
  - each part's material carries the game's material name (<part>UV_00N/TEXFACE/<part>UV_00N.tga, defined in
    media/tumbu/robot00N/robot00N.material), like the arena does.
  With --save they are written back into the .blend; otherwise the export still uses them but the file is left alone.

Export layout (what the game expects; the 2011 exporter did the same):
  - one .mesh per part, in the part object's own space (the parts are centred on their origins; the attach points
    in robot00N.object rely on it), Y-up as in the file (no axis conversion). Quads split along their shorter
    diagonal and normals as Blender has them (custom normals included), through a temporary Triangulate modifier;
    tangents generated by Ogre (OgreMeshUpgrader -t), since Blender cannot store tangents;
  - one .skeleton per part (head_00N.skeleton, ...): the robot's armature, but in the part's space. blender2ogre
    writes the skeleton in the armature's space, so the root bones' rest positions are moved by the offset between
    the armature's and the part's origins in the exported XML (move_skeleton_to_part), then converted to binary;
  - the 14 actions as animations, baked at every frame and trimmed of keys that change nothing, only the bones each
    action moves (the game blends animations cumulatively). blender2ogre takes the animations from NLA strips: one
    temporary strip per action, over the action's frame range.
"""
import bpy
import os
import re
import subprocess
import sys
import xml.etree.ElementTree as ET

import addon_utils

sys.dont_write_bytecode = True

sys.path.append(os.path.dirname(os.path.abspath(__file__)))
import robot_check  # noqa: E402

PARTS = ("head", "body", "leftArm", "rightArm", "legs")
FPS = 30
MAX_WEIGHTS = 4
MIN_WEIGHT = 0.01
CONVERTER = os.path.join("D:" + os.sep, "TumbuDeps", "modern", "install", "bin", "OgreXMLConverter.exe")
UPGRADER = os.path.join(os.path.dirname(CONVERTER), "OgreMeshUpgrader.exe")
CHECKS = []

args = sys.argv[sys.argv.index("--") + 1:] if "--" in sys.argv else []
OUT = args[0]
SAVE = "--save" in args


def log(message):
    print("[ROBOT-EXPORT] " + message, flush=True)


def robot_parts(number):
    parts = {}
    for ob in bpy.data.objects:
        m = re.match(r"(%s)_%s$" % ("|".join(PARTS), number), ob.name)
        if m and ob.type == 'MESH':
            parts[m.group(1)] = ob
    missing = [p for p in PARTS if p not in parts]
    if missing:
        raise SystemExit("parts not found: " + ", ".join(missing))
    return [parts[p] for p in PARTS]


def fix_weights(ob, bones):
    """Removes vertex groups that are not bones, normalises, removes weights below MIN_WEIGHT, keeps the MAX_WEIGHTS
    largest per vertex and normalises again."""
    # Groups named after no bone (body_L, Group, Spin1, ... left from 2011) deform nothing, in Blender or in Ogre, but
    # Blender's limit and normalise operators would count them.
    def signature():
        names = {g.index: g.name for g in ob.vertex_groups}
        return [sorted((names[g.group], round(g.weight, 4)) for g in v.groups if g.weight > 0) for v in ob.data.vertices]

    original = signature()
    dead = [g.name for g in ob.vertex_groups if g.name not in bones]
    for name in dead:
        ob.vertex_groups.remove(ob.vertex_groups[name])
    over = sum(1 for v in ob.data.vertices if sum(1 for g in v.groups if g.weight > 0) > MAX_WEIGHTS)
    bpy.ops.object.select_all(action='DESELECT')
    ob.select_set(True)
    bpy.context.view_layer.objects.active = ob
    # Normalise first: some vertices only have tiny weights (0.005 on one bone, 0.009 on another), which Ogre (and the
    # 2011 exporter) scale up to 1; dropping small weights before that would leave them on no bone. keep_single keeps
    # at least the largest one either way.
    # Repeated until nothing changes: a weight just above MIN_WEIGHT can fall below it after the last normalisation,
    # and the export must leave a saved file exactly as it found it.
    bpy.ops.object.vertex_group_normalize_all(group_select_mode='ALL', lock_active=False)
    for _ in range(5):
        before_pass = signature()
        bpy.ops.object.vertex_group_clean(group_select_mode='ALL', limit=MIN_WEIGHT, keep_single=True)
        bpy.ops.object.vertex_group_limit_total(group_select_mode='ALL', limit=MAX_WEIGHTS)
        bpy.ops.object.vertex_group_normalize_all(group_select_mode='ALL', lock_active=False)
        if signature() == before_pass:
            break
    unbound = sum(1 for v in ob.data.vertices if not any(g.weight > 0 for g in v.groups))
    if unbound:
        raise SystemExit("%s: %d vertices follow no bone" % (ob.name, unbound))
    after = max((sum(1 for g in v.groups if g.weight > 0) for v in ob.data.vertices), default=0)
    if after > MAX_WEIGHTS:
        raise SystemExit("%s: still %d weights on a vertex" % (ob.name, after))
    changed = sum(1 for a, b in zip(original, signature()) if a != b)
    return dead, over, changed


def fix_source(parts):
    scene = bpy.context.scene
    changes = []
    if scene.render.fps != FPS or scene.render.fps_base != 1.0:
        changes.append("fps %s/%.4f -> %d" % (scene.render.fps, scene.render.fps_base, FPS))
        scene.render.fps = FPS
        scene.render.fps_base = 1.0
    for ob in parts:
        dead, over, changed = fix_weights(ob, {b.name for b in ob.find_armature().data.bones})
        if dead:
            changes.append("%s: removed vertex groups that are no bone: %s" % (ob.name, ", ".join(dead)))
        if changed:
            changes.append("%s: weights of %d vertices changed (%d had more than %d bones)" % (
                ob.name, changed, over, MAX_WEIGHTS))
        for slot in ob.material_slots:
            m = slot.material
            if m and "/TEXFACE/" not in m.name:
                game = "%s/TEXFACE/%s.tga" % (m.name, m.name)
                changes.append("material %s -> %s" % (m.name, game))
                m.name = game
    return changes


def add_export_strips(arm):
    """One temporary NLA track per action (blender2ogre exports the actions it finds in NLA strips)."""
    if arm.animation_data is None:
        arm.animation_data_create()
    for action in sorted(bpy.data.actions, key=lambda a: a.name):
        track = arm.animation_data.nla_tracks.new()
        track.name = "ogre_" + action.name
        start, end = action.frame_range
        strip = track.strips.new(action.name, int(start), action)
        strip.action_frame_start = start
        strip.action_frame_end = end


def move_skeleton_to_part(skeleton_xml, delta):
    """blender2ogre writes the skeleton in the armature's space; the game needs it in the part's space (the meshes are
    centred on their own origins). Only the root bones' rest positions change (their parent space is the model space),
    which is an exact translation. Moving the bones in Blender's edit mode instead would rebuild their orientations
    from head, tail and roll, and for the 2011 bones that flips some rolls by 180 degrees, so the animations change."""
    tree = ET.parse(skeleton_xml)
    root = tree.getroot()
    children = {p.get("bone") for p in root.find("bonehierarchy")}
    for bone in root.find("bones"):
        if bone.get("name") not in children:
            position = bone.find("position")
            for axis, value in zip("xyz", delta):
                position.set(axis, "%.6f" % (float(position.get(axis)) + value))
    tree.write(skeleton_xml, encoding="UTF-8", xml_declaration=True)
    binary = skeleton_xml[:-len(".xml")]
    result = subprocess.run([CONVERTER, "-q", skeleton_xml, binary], capture_output=True, text=True,
                            cwd=os.path.dirname(skeleton_xml))
    if result.returncode != 0 or not os.path.exists(binary):
        raise SystemExit("OgreXMLConverter failed on %s: %s" % (skeleton_xml, result.stdout + result.stderr))


def export_part(ob, arm, out):
    from io_ogre import api
    # From the armature's space to the part's space (the armature and the parts are unrotated and unscaled).
    delta = arm.matrix_world.translation - ob.matrix_world.translation
    bpy.ops.object.select_all(action='DESELECT')
    ob.select_set(True)
    bpy.context.view_layer.objects.active = ob
    # blender2ogre triangulates with bmesh, which loses the parts' custom normals (they are stored relative to each
    # corner's own frame, and the frames change when faces split): hand it triangles that already carry them.
    triangulate = ob.modifiers.new("ogre_export_triangles", 'TRIANGULATE')
    triangulate.keep_custom_normals = True
    # Quads split along their shorter diagonal: what the 2011 exporter did (95 to 100 % of its triangles; FIXED matched
    # half). The split decides how the shading is interpolated across a quad that is not flat.
    triangulate.quad_method = 'SHORTEST_DIAGONAL'
    triangulate.min_vertices = 4
    try:
        api.dot_mesh(ob, out, force_name=ob.name, overwrite=True, tangents=0)
    finally:
        ob.modifiers.remove(triangulate)
    # Tangents (for the normal maps) are derived data Blender cannot store: Ogre's own calculator makes them, as for the
    # 2011 files (Blender's tangents differed by up to 42 degrees from those, Ogre's by a few).
    mesh_file = os.path.join(out, ob.name + ".mesh")
    result = subprocess.run([UPGRADER, "-t", "-ts", "4", mesh_file], capture_output=True, text=True, cwd=out)
    if result.returncode != 0:
        raise SystemExit("OgreMeshUpgrader failed on %s: %s" % (mesh_file, result.stdout + result.stderr))
    api.dot_skeleton(ob, out, force_name=ob.name, overwrite=True, exported_armatures=[])
    mesh_xml = os.path.join(out, ob.name + ".mesh.xml")
    skeleton_xml = os.path.join(out, ob.name + ".skeleton.xml")
    move_skeleton_to_part(skeleton_xml, delta)

    # Blender against the exported files: weights per vertex, every bone at every frame of every action.
    weight_problems, weight_diff, vertices, normal_diff = robot_check.check_weights(ob, mesh_xml, skeleton_xml)
    pose_problems, pos_diff, rot_diff = robot_check.check_animation(arm, skeleton_xml, FPS, delta)
    status = "OK" if not weight_problems and not pose_problems else "DIFFERS"
    log("%s %s: %d vertices, weights within %.6f, normals within %.3f deg; bones within %.6f units, %.6f rad over all "
        "frames" % (status, ob.name, vertices, weight_diff, normal_diff, pos_diff, rot_diff))
    for p in weight_problems + pose_problems:
        log("  " + p)
    CHECKS.append(status == "OK")


def main():
    if "io_ogre" not in bpy.context.preferences.addons:
        addon_utils.enable("io_ogre")
    from io_ogre import config
    # The converter path: blender2ogre keeps it per Blender version (this one may not have it set yet).
    config.update(OGRETOOLS_XML_CONVERTER=CONVERTER)
    config.update(SWAP_AXIS='xyz', TRIM_BONE_WEIGHTS=0.0, ONLY_KEYFRAMED_BONES=True, ONLY_KEYFRAMES=False,
                  OPTIMISE_ANIMATIONS=True, ARMATURE_ANIMATION=True, SHARED_ARMATURE=False, EXPORT_XML_DELETE=False)

    name = os.path.splitext(os.path.basename(bpy.data.filepath))[0]     # robot00N
    number = name[-3:]
    parts = robot_parts(number)
    arm = parts[0].find_armature()
    for ob in parts:
        if ob.find_armature() != arm:
            raise SystemExit("%s is not on %s" % (ob.name, arm.name))
    if arm.parent or any(abs(s - 1.0) > 1e-6 for s in arm.scale) or any(abs(r) > 1e-6 for r in arm.rotation_euler):
        raise SystemExit("%s must be unparented, unrotated and unscaled" % arm.name)

    changes = fix_source(parts)
    for c in changes:
        log("%s: %s" % (name, c))
    if not changes:
        log("%s: source already clean" % name)
    if SAVE and changes:
        bpy.ops.wm.save_mainfile()
        log("%s: saved %s" % (name, bpy.data.filepath))

    out = os.path.join(OUT, name)
    os.makedirs(out, exist_ok=True)
    add_export_strips(arm)
    for ob in parts:
        export_part(ob, arm, out)
        log("%s: exported %s" % (name, ob.name))
    if not all(CHECKS):
        raise SystemExit("%s: the export does not match Blender (see above)" % name)
    log("%s: all parts match Blender" % name)


main()
